# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'

target 'TheDogs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheDogs

  target 'TheDogsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheDogsUITests' do
    # Pods for testing
  end

end
